import Head from 'next/head';
import React, { useEffect, useState } from 'react';
import Card from '../components/card'
import styles from '../styles/Home.module.css';
import Link from 'next/link';

export default function Home(props) {
  const { movies } = props;
  console.log('props', props);

  return (
    <>
      <Head>
        <title>Movie Watchlist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container home'>
        <section className={styles.section}>
          <Link href='/list/popular'>
            <a className={styles.heading}>
              Popular Movies
            </a>
          </Link>

          <div className='flex flex-wrap -mx-2'>
            <CardDeck data={movies.popular} />
          </div>
        </section>
        <section className={styles.section}>
          <Link href='/list/playing'>
            <a className={styles.heading}>
              Now Playing
            </a>
          </Link>

          <div className='flex flex-wrap -mx-2'>
            <CardDeck data={movies.playing} />
          </div>
        </section>
        <section className={styles.section}>
          <Link href='/list/upcoming'>
            <a className={styles.heading}>
              Upcoming
            </a>
          </Link>

          <div className='flex flex-wrap -mx-2'>
            <CardDeck data={movies.upcoming} />
          </div>
        </section>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const popular_fetch = await fetch('https://api.themoviedb.org/3/movie/popular?api_key=519a976872b6d6cc0f7179573ca7e334&language=en-US&page=1');
  const popular_movies = await popular_fetch.json();
  const upcoming_fetch = await fetch('https://api.themoviedb.org/3/movie/upcoming?api_key=519a976872b6d6cc0f7179573ca7e334&language=en-US&page=1');
  const upcoming_movies = await upcoming_fetch.json();
  const playing_fetch = await fetch('https://api.themoviedb.org/3/movie/now_playing?api_key=519a976872b6d6cc0f7179573ca7e334&language=en-US&page=1');
  const playing_movies = await playing_fetch.json();
  const movies = {
    popular: popular_movies.results.slice(0, 3),
    upcoming: upcoming_movies.results.slice(0, 3),
    playing: playing_movies.results.slice(0, 3),
  }
  return {
    props: {
      movies: movies  // will be passed to the page component as props
    },
    revalidate: 60,
  }
}

function CardDeck({ data }) {
  return data.map(d => {
    return (
      <Card key={'card-' + d.id} id={d.id} title={d.title} poster_path={d.poster_path} vote_average={d.vote_average} vote_count={d.vote_count} />
    )
  })
}
